# import = [
#   # "~/.config/alacritty/themes/ayu_dark.toml",
#   # "~/.config/alacritty/themes/doom_one.toml",
#   # "~/.config/alacritty/catppuccin-latte.toml"
#   # "~/.config/alacritty/themes/drakula.toml"
# ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[window]
padding.x = 10
padding.y = 10

decorations = "full"
opacity = 0.7
blur = true
dynamic_padding = false

[colors.primary]
background = "0x121d1f"
foreground = "0x6f7981"

[colors.normal]
black = "0x121d1f"
red = "0x4a5156"
green = "0x655559"
yellow = "0x505d63"
blue = "0x59666c"
magenta = "0x677279"
cyan = "0x707c83"
white = "0xb2b8bb"

# [colors.bright]
# black = "0x"
# red = "0xF07178"
# green = "0xC2D94C"
# yellow = "0xFFB454"
# blue = "0x59C2FF"
# magenta = "0xFFEE99"
# cyan = "0x95E6CB"
# white = "0xFFFFFF"
#
# [[keyboard.bindings]]
# key = "N"
# mods = "Command"
# action = "SpawnNewInstance"
#
# [[keyboard.bindings]]
# key = "Space"
# mods = "Alt"
# chars = " "
#
# [[keyboard.bindings]]
# key = "Back"
# mods = "Super"
# chars = "\u0015"
#
# [[keyboard.bindings]]
# key = "Left"
# mods = "Alt"
# chars = "\u001bb"
#
# [[keyboard.bindings]]
# key = "Right"
# mods = "Alt"
# chars = "\u001bf"
#
# [[keyboard.bindings]]
# key = "Left"
# mods = "Command"
# chars = "\u001bOH"
# mode = "AppCursor"
#
# [[keyboard.bindings]]
# key = "Right"
# mods = "Command"
# chars = "\u001bOF"
# mode = "AppCursor"
#
# [[keyboard.bindings]]
# key = "R"
# mods = "Command"
# chars = "\u001bR"
