#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#1
# 2
# 3 
# 4 
# firefox
# discord
# steam 
# heroic
# RL !
# stalcraft !
# nvim !
# youtube !
# youtube-music 
bspc monitor -d 1 2 3 4 "󰈹" "" "" "" "" "󱎓" "󰎅" "󰠮"
# bspc monitor -d 1 2 3 4 "󰈹" "" "s" "h" " " " " " " " " "" 

bspc config border_width 5.5
bspc config window_gap 14

bspc config focused_border_color "#4e3d41"
bspc config normal_border_color "#322628"
# bspc config focused_border_color "#4f6f68"
# bspc config normal_border_color "#384a4b"

xsetroot -cursor_name left_ptr

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop = "^5" 
bspc rule -a discord desktop =  "^6"
bspc rule -a vesktop desktop =  "^6"
bspc rule -a heroic desktop =  "^7"
bspc rule -a steam desktop = "^7" 
bspc rule -a "TelegramDesktop" desktop = "^8"
bspc rule -a neovide desktop = "^9"
bspc rule -a "steam_app_945360" desktop = "^10"
bspc rule -a "steam_app_1818450" desktop = "^10"
bspc rule -a "YouTube Music" desktop = "^11"
bspc rule -a "obsidian" desktop = "^12"

$HOME/.config/polybar/launch.sh &
picom -b &
sh ~/.fehbg
