fork = true
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" 
no-multigrid = true
srgb = true
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = true
[font]
size = 15
hinting = "full"
edging = "antialias"
[[font.normal]]
family = "CaskaydiaCove Nerd Font"
