[font]
    normal = [] # Will use the bundled Fira Code Nerd Font by default
    size = 5
fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
title-hidden = true
vsync = true
wsl = false
